### ISSUE TITLE
susy vs. foundation6?

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/gulp-frontend-boilerplate#17]
we have still susy in our bower.json. what do you think should be our standard grid for future projects susy or foundation. @janrembold you used both in projects whats you oppinion?

**Comment by janrembold** [comment]
I thought about adding all 3 main grids to the boilerplate: bootstrap, foundation and susy. 
Because all of them would be simple SASS imports they wouldn't pollute our final css files.

Benefits would be a faster kickstart with whatever grid we use and a working and tested default configuration for them.

The only disadvantage (that I see) would be too much bower components initially.

**Comment by timomayer** [comment]
i prefer to have one of them in the boilerplate cause we should be as consitent in our projects as possible. if someone has a good reason to use another one in a single project he can easly change that

**Comment by janrembold** [comment]
I don't think it is possible to stay consistent over all our projects and all three have there pros and cons. 

> if someone has a good reason to use another one in a single project he can easily change that
To be really consistent that would mean to remove all grids, because you could add the best choice on your own at each project start. 

Another reason to add all three grids would be that some configurations are a little bit tricky to get a clean start. So a predefined "best practice config" would help here too.

**Comment by timomayer** [comment]
not exactly what i meant. with consistent i meant we should not change the grid in every new project without any reason just for fun or randomly use one of this 3 ;) we should decide for one which fits most our projects best for now and put it in the boilerplate as default like we do with jquery as default js lib. we should constantly evaluate if there is a new and better one and then decide if we should put that one as new default into the boilerplate.

of cause if we have a special projects which benefits from another grid we should use that grid in this special project but put it only in this stecial project and stay with our standard in the boilerplate.

**Comment by janrembold** [comment]
ok, got your point. with this in mind I would go with foundation at the moment. here you can decide between a well-tested predefined grid or a custom include-based grid (like susy). so the best from both worlds out of a single box.

**Comment by timomayer** [comment]
+1 for foundation

**Comment by janrembold** [comment]
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/22
